import type { Metadata } from "next";

import Header from "@/components/header";
import Providers from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next-Reddit-Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container mx-auth px-4 max-w-6xl">
          <Providers>
            <Header />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
